// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrV2egRahRMI1c-uCRd-CKAfttzyS287Q',
    appId: '1:101926910962:web:eb6618554e951d0a47896b',
    messagingSenderId: '101926910962',
    projectId: 'flutter-natures',
    authDomain: 'flutter-natures.firebaseapp.com',
    storageBucket: 'flutter-natures.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGAS2gf0e5G6zGYcAmP7Wo0sGHvS7q1BA',
    appId: '1:101926910962:android:fd7139783e0d966647896b',
    messagingSenderId: '101926910962',
    projectId: 'flutter-natures',
    storageBucket: 'flutter-natures.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdSgQnjWL99iCvRGwgBJ76IgHLv0zHxIQ',
    appId: '1:101926910962:ios:366a6ecec0566c2c47896b',
    messagingSenderId: '101926910962',
    projectId: 'flutter-natures',
    storageBucket: 'flutter-natures.appspot.com',
    iosBundleId: 'com.example.theNaturesApp',
  );
}
